In [1]:
from google.colab import drive
drive.mount('/content/drive',force_remount=True)

Mounted at /content/drive


In [65]:
import pandas as pd
fly_data = pd.read_csv("/content/drive/MyDrive/fly-data/Marketing Project-Flight data.csv")
survey_data = pd.read_csv("/content/drive/MyDrive/fly-data/Marketing Project-Survey data.csv")

In [66]:
survey_data = survey_data.rename(columns = {'CustomerId':'CustomerID'})

In [67]:
fly_data.isna().sum()

CustomerID                  0
Gender                      0
CustomerType             9099
Age                         0
TypeTravel               9088
Class                       0
Flight_Distance             0
DepartureDelayin_Mins       0
ArrivalDelayin_Mins       284
dtype: int64

In [68]:
survey_data.isna().sum()

CustomerID                              0
Satisfaction                            0
Seat_comfort                            0
Departure.Arrival.time_convenient    8244
Food_drink                           8181
Gate_location                           0
Inflightwifi_service                    0
Inflight_entertainment                  0
Online_support                          0
Ease_of_Onlinebooking                   0
Onboard_service                      7179
Leg_room_service                        0
Baggage_handling                        0
Checkin_service                         0
Cleanliness                             0
Online_boarding                         0
dtype: int64

In [69]:
merged = pd.merge(fly_data, survey_data, on="CustomerID")

In [70]:
values = {"CustomerType": "Loyal Customer", "TypeTravel": "Business travel", "ArrivalDelayin_Mins": 0.0, "Departure.Arrival.time_convenient": "good","Food_drink":"acceptable","Onboard_service": "good"}
merged.fillna(value=values,inplace=True)

In [71]:
########
merged['Seat_comfort'].replace(['excellent', 'good','acceptable','need improvement', 'poor', 'extremely poor'],[6,5,4,3,2,1], inplace=True)
merged['Food_drink'].replace(['excellent', 'good','acceptable','need improvement', 'poor', 'extremely poor'],[6,5,4,3,2,1], inplace=True)
merged['Departure.Arrival.time_convenient'].replace(['excellent', 'good','acceptable','need improvement', 'poor', 'extremely poor'],[6,5,4,3,2,1], inplace=True)
merged['Inflightwifi_service'].replace(['excellent', 'good','acceptable','need improvement', 'poor', 'extremely poor'],[6,5,4,3,2,1], inplace=True)
merged['Inflight_entertainment'].replace(['excellent', 'good','acceptable','need improvement', 'poor', 'extremely poor'],[6,5,4,3,2,1], inplace=True)
merged['Online_support'].replace(['excellent', 'good','acceptable','need improvement', 'poor', 'extremely poor'],[6,5,4,3,2,1], inplace=True)
merged['Ease_of_Onlinebooking'].replace(['excellent', 'good','acceptable','need improvement', 'poor', 'extremely poor'],[6,5,4,3,2,1], inplace=True)
merged['Onboard_service'].replace(['excellent', 'good','acceptable','need improvement', 'poor', 'extremely poor'],[6,5,4,3,2,1], inplace=True)
merged['Leg_room_service'].replace(['excellent', 'good','acceptable','need improvement', 'poor', 'extremely poor'],[6,5,4,3,2,1], inplace=True)
merged['Baggage_handling'].replace(['excellent', 'good','acceptable','need improvement', 'poor', 'extremely poor'],[6,5,4,3,2,1], inplace=True)
merged['Checkin_service'].replace(['excellent', 'good','acceptable','need improvement', 'poor', 'extremely poor'],[6,5,4,3,2,1], inplace=True)
merged['Cleanliness'].replace(['excellent', 'good','acceptable','need improvement', 'poor', 'extremely poor'],[6,5,4,3,2,1], inplace=True)
merged['Online_boarding'].replace(['excellent', 'good','acceptable','need improvement', 'poor', 'extremely poor'],[6,5,4,3,2,1], inplace=True)
#########
merged['Gate_location'].replace(['very convinient','manageable', 'Convinient','need improvement','Inconvinient', 'very inconvinient'],[6,5,4,3,2,1], inplace=True)

In [72]:
merged['Gender'].replace(['Female', 'Male'],[1,0], inplace=True)
merged['CustomerType'].replace(['Loyal Customer','disloyal Customer'],[1,0], inplace=True)
merged['TypeTravel'].replace(['Business travel', 'Personal Travel'],[1,0], inplace=True)
merged['Class'].replace(['Business','Eco','Eco Plus'],[2,1,0],inplace=True)
merged["Satisfaction"].replace(['satisfied','neutral or dissatisfied'],[1,0],inplace=True)

In [73]:
merged.head()

CustomerID  Gender  CustomerType  Age  TypeTravel  Class  Flight_Distance  \
0      149965       1             1   65           0      1              265   
1      149966       1             1   15           0      1             2138   
2      149967       1             1   60           0      1              623   
3      149968       1             1   70           0      1              354   
4      149969       0             1   30           1      1             1894   

   DepartureDelayin_Mins  ArrivalDelayin_Mins  Satisfaction  ...  \
0                      0                  0.0             1  ...   
1                      0                  0.0             1  ...   
2                      0                  0.0             1  ...   
3                      0                  0.0             1  ...   
4                      0                  0.0             1  ...   

   Inflightwifi_service  Inflight_entertainment  Online_support  \
0                     3                       5               3   
1                     3                       1               3   
2                     4                       5               4   
3                     5                       4               5   
4                     3                       1               3   

   Ease_of_Onlinebooking  Onboard_service  Leg_room_service  Baggage_handling  \
0                      4                4                 1                 4   
1                      3                5                 4                 5   
2                      2                2                 1                 2   
3                      3                3                 1                 3   
4                      3                6                 5                 6   

   Checkin_service  Cleanliness  Online_boarding  
0                6            4                3  
1                5            5                3  
2                5            2                4  
3                5            3                6  
4                6            5                3  

[5 rows x 24 columns]

In [74]:
X = merged[['Gender', 'CustomerType', 'Age', 'TypeTravel', 'Class',
       'Flight_Distance', 'DepartureDelayin_Mins', 'ArrivalDelayin_Mins','Seat_comfort', 'Departure.Arrival.time_convenient',
       'Food_drink', 'Gate_location', 'Inflightwifi_service',
       'Inflight_entertainment', 'Online_support', 'Ease_of_Onlinebooking',
       'Onboard_service', 'Leg_room_service', 'Baggage_handling',
       'Checkin_service', 'Cleanliness', 'Online_boarding']]
y = merged[['Satisfaction']]

In [75]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=None,test_size=0.20)

In [76]:
X_train = X_train.drop(['Gender', 'Baggage_handling','Cleanliness','Checkin_service','Departure.Arrival.time_convenient','TypeTravel','Gate_location','Inflightwifi_service','ArrivalDelayin_Mins','DepartureDelayin_Mins'], axis=1)
X_test = X_test.drop(['Gender', 'Baggage_handling','Cleanliness','Checkin_service','Departure.Arrival.time_convenient','TypeTravel','Gate_location','Inflightwifi_service','ArrivalDelayin_Mins','DepartureDelayin_Mins'], axis=1)

In [77]:
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
def calculate_results(y_true, y_pred):
  model_accuracy = accuracy_score(y_true, y_pred) * 100
  model_precision, model_recall, model_f1, _ = precision_recall_fscore_support(y_true, y_pred, average="weighted")
  model_results = {"accuracy": model_accuracy,
                  "precision": model_precision,
                  "recall": model_recall,
                  "f1": model_f1}
  return model_results

In [48]:
#from sklearn.preprocessing import StandardScaler
#ss = StandardScaler()
#X_train = ss.fit_transform(X_train)
#X_test = ss.transform(X_test)

In [78]:
y_train =y_train["Satisfaction"].ravel()
y_test=y_test["Satisfaction"].ravel()

In [79]:
import lightgbm as lgb
clf = lgb.LGBMClassifier()
clf.fit(X_train, y_train)

LGBMClassifier()

In [80]:
y_pred=clf.predict(X_test)
calculate_results(y_true=y_test,y_pred=y_pred)

{'accuracy': 92.96084469863617,
 'precision': 0.9297418322640507,
 'recall': 0.9296084469863617,
 'f1': 0.9296445551739732}

In [81]:
y_pred[:100]

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1])

In [82]:
y_test[:100]

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1])

In [83]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_true=y_test, 
                 y_pred=y_pred)

array([[7643,  588],
       [ 692, 9261]])

In [89]:
import numpy as np
a = np.array([[1,25,1,256,5,6,5,6,6,6,6,6]])
clf.predict(a)

array([1])

In [90]:
import pickle
pickle.dump(clf,open('clf_model.pkl','wb'))