In [2]:
import pandas as pd
fly_data = pd.read_csv("Marketing Project-Flight data.csv")
survey_data = pd.read_csv("Marketing Project-Survey data.csv")

In [3]:
survey_data = survey_data.rename(columns = {'CustomerId':'CustomerID'})

In [4]:
fly_data.isna().sum()

CustomerID                  0
Gender                      0
CustomerType             9099
Age                         0
TypeTravel               9088
Class                       0
Flight_Distance             0
DepartureDelayin_Mins       0
ArrivalDelayin_Mins       284
dtype: int64

In [5]:
survey_data.isna().sum()

CustomerID                              0
Satisfaction                            0
Seat_comfort                            0
Departure.Arrival.time_convenient    8244
Food_drink                           8181
Gate_location                           0
Inflightwifi_service                    0
Inflight_entertainment                  0
Online_support                          0
Ease_of_Onlinebooking                   0
Onboard_service                      7179
Leg_room_service                        0
Baggage_handling                        0
Checkin_service                         0
Cleanliness                             0
Online_boarding                         0
dtype: int64

In [6]:
merged = pd.merge(fly_data, survey_data, on="CustomerID")

In [7]:
values = {"CustomerType": "Loyal Customer", "TypeTravel": "Business travel", "ArrivalDelayin_Mins": 0.0, "Departure.Arrival.time_convenient": "good","Food_drink":"acceptable","Onboard_service": "good"}
merged.fillna(value=values,inplace=True)

In [28]:
merged.head()

CustomerID  Gender  CustomerType  Age  TypeTravel  Class  Flight_Distance  \
0      149965       1             1   65           0      1              265   
1      149966       1             1   15           0      1             2138   
2      149967       1             1   60           0      1              623   
3      149968       1             1   70           0      1              354   
4      149969       0             1   30           1      1             1894   

   DepartureDelayin_Mins  ArrivalDelayin_Mins  Satisfaction  ...  \
0                      0                  0.0             1  ...   
1                      0                  0.0             1  ...   
2                      0                  0.0             1  ...   
3                      0                  0.0             1  ...   
4                      0                  0.0             1  ...   

   Inflightwifi_service  Inflight_entertainment  Online_support  \
0                     3                       4               3   
1                     3                       0               3   
2                     3                       4               3   
3                     4                       3               4   
4                     3                       0               3   

   Ease_of_Onlinebooking  Onboard_service  Leg_room_service  Baggage_handling  \
0                      3                3                 0                 3   
1                      3                4                 3                 4   
2                      1                1                 0                 1   
3                      3                3                 0                 3   
4                      3                5                 4                 5   

   Checkin_service  Cleanliness  Online_boarding  
0                5            3                3  
1                4            4                3  
2                4            1                3  
3                4            3                5  
4                5            4                3  

[5 rows x 24 columns]

In [33]:
merged.loc[merged['Satisfaction'] == 1].head(3)

CustomerID  Gender  CustomerType  Age  TypeTravel  Class  Flight_Distance  \
0      149965       1             1   65           0      1              265   
1      149966       1             1   15           0      1             2138   
2      149967       1             1   60           0      1              623   

   DepartureDelayin_Mins  ArrivalDelayin_Mins  Satisfaction  ...  \
0                      0                  0.0             1  ...   
1                      0                  0.0             1  ...   
2                      0                  0.0             1  ...   

   Inflightwifi_service  Inflight_entertainment  Online_support  \
0                     3                       4               3   
1                     3                       0               3   
2                     3                       4               3   

   Ease_of_Onlinebooking  Onboard_service  Leg_room_service  Baggage_handling  \
0                      3                3                 0                 3   
1                      3                4                 3                 4   
2                      1                1                 0                 1   

   Checkin_service  Cleanliness  Online_boarding  
0                5            3                3  
1                4            4                3  
2                4            1                3  

[3 rows x 24 columns]

In [31]:
merged["Flight_Distance"].mean()

1981.6294422385251

In [9]:
########
merged['Seat_comfort'].replace(['excellent', 'good','acceptable','need improvement', 'poor', 'extremely poor'],[5,4,3,3,1,0], inplace=True)
merged['Food_drink'].replace(['excellent', 'good','acceptable','need improvement', 'poor', 'extremely poor'],[5,4,3,3,1,0], inplace=True)
merged['Departure.Arrival.time_convenient'].replace(['excellent', 'good','acceptable','need improvement', 'poor', 'extremely poor'],[5,4,3,3,1,0], inplace=True)
merged['Inflightwifi_service'].replace(['excellent', 'good','acceptable','need improvement', 'poor', 'extremely poor'],[5,4,3,3,1,0], inplace=True)
merged['Inflight_entertainment'].replace(['excellent', 'good','acceptable','need improvement', 'poor', 'extremely poor'],[5,4,3,3,1,0], inplace=True)
merged['Online_support'].replace(['excellent', 'good','acceptable','need improvement', 'poor', 'extremely poor'],[5,4,3,3,1,0], inplace=True)
merged['Ease_of_Onlinebooking'].replace(['excellent', 'good','acceptable','need improvement', 'poor', 'extremely poor'],[5,4,3,3,1,0], inplace=True)
merged['Onboard_service'].replace(['excellent', 'good','acceptable','need improvement', 'poor', 'extremely poor'],[5,4,3,3,1,0], inplace=True)
merged['Leg_room_service'].replace(['excellent', 'good','acceptable','need improvement', 'poor', 'extremely poor'],[5,4,3,3,1,0], inplace=True)
merged['Baggage_handling'].replace(['excellent', 'good','acceptable','need improvement', 'poor', 'extremely poor'],[5,4,3,3,1,0], inplace=True)
merged['Checkin_service'].replace(['excellent', 'good','acceptable','need improvement', 'poor', 'extremely poor'],[5,4,3,3,1,0], inplace=True)
merged['Cleanliness'].replace(['excellent', 'good','acceptable','need improvement', 'poor', 'extremely poor'],[5,4,3,3,1,0], inplace=True)
merged['Online_boarding'].replace(['excellent', 'good','acceptable','need improvement', 'poor', 'extremely poor'],[5,4,3,3,1,0], inplace=True)
#########
merged['Gate_location'].replace(['very convinient','manageable', 'Convinient','need improvement','Inconvinient', 'very inconvinient'],[6,5,4,3,2,1], inplace=True)

In [10]:
merged['Gender'].replace(['Female', 'Male'],[1,0], inplace=True)
merged['CustomerType'].replace(['Loyal Customer','disloyal Customer'],[1,0], inplace=True)
merged['TypeTravel'].replace(['Business travel', 'Personal Travel'],[1,0], inplace=True)
merged['Class'].replace(['Business','Eco','Eco Plus'],[2,1,0],inplace=True)
merged["Satisfaction"].replace(['satisfied','neutral or dissatisfied'],[1,0],inplace=True)

In [11]:
merged.head()

CustomerID  Gender  CustomerType  Age  TypeTravel  Class  Flight_Distance  \
0      149965       1             1   65           0      1              265   
1      149966       1             1   15           0      1             2138   
2      149967       1             1   60           0      1              623   
3      149968       1             1   70           0      1              354   
4      149969       0             1   30           1      1             1894   

   DepartureDelayin_Mins  ArrivalDelayin_Mins  Satisfaction  ...  \
0                      0                  0.0             1  ...   
1                      0                  0.0             1  ...   
2                      0                  0.0             1  ...   
3                      0                  0.0             1  ...   
4                      0                  0.0             1  ...   

   Inflightwifi_service  Inflight_entertainment  Online_support  \
0                     3                       4               3   
1                     3                       0               3   
2                     3                       4               3   
3                     4                       3               4   
4                     3                       0               3   

   Ease_of_Onlinebooking  Onboard_service  Leg_room_service  Baggage_handling  \
0                      3                3                 0                 3   
1                      3                4                 3                 4   
2                      1                1                 0                 1   
3                      3                3                 0                 3   
4                      3                5                 4                 5   

   Checkin_service  Cleanliness  Online_boarding  
0                5            3                3  
1                4            4                3  
2                4            1                3  
3                4            3                5  
4                5            4                3  

[5 rows x 24 columns]

In [12]:
X = merged[['Gender', 'CustomerType', 'Age', 'TypeTravel', 'Class',
       'Flight_Distance', 'DepartureDelayin_Mins', 'ArrivalDelayin_Mins','Seat_comfort', 'Departure.Arrival.time_convenient',
       'Food_drink', 'Gate_location', 'Inflightwifi_service',
       'Inflight_entertainment', 'Online_support', 'Ease_of_Onlinebooking',
       'Onboard_service', 'Leg_room_service', 'Baggage_handling',
       'Checkin_service', 'Cleanliness', 'Online_boarding']]
y = merged[['Satisfaction']]

In [13]:
import sklearn
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=None,test_size=0.20)

In [14]:
X_train = X_train.drop(['Gender', 'Baggage_handling','Cleanliness','Checkin_service','Departure.Arrival.time_convenient','TypeTravel','Gate_location','Inflightwifi_service','ArrivalDelayin_Mins','DepartureDelayin_Mins'], axis=1)
X_test = X_test.drop(['Gender', 'Baggage_handling','Cleanliness','Checkin_service','Departure.Arrival.time_convenient','TypeTravel','Gate_location','Inflightwifi_service','ArrivalDelayin_Mins','DepartureDelayin_Mins'], axis=1)

In [15]:
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
def calculate_results(y_true, y_pred):
  model_accuracy = accuracy_score(y_true, y_pred) * 100
  model_precision, model_recall, model_f1, _ = precision_recall_fscore_support(y_true, y_pred, average="weighted")
  model_results = {"accuracy": model_accuracy,
                  "precision": model_precision,
                  "recall": model_recall,
                  "f1": model_f1}
  return model_results

In [16]:
y_train =y_train["Satisfaction"].ravel()
y_test=y_test["Satisfaction"].ravel()

In [17]:
import lightgbm as lgb
clf = lgb.LGBMClassifier()
clf.fit(X_train, y_train)

LGBMClassifier()

In [18]:
y_pred=clf.predict(X_test)
calculate_results(y_true=y_test,y_pred=y_pred)

{'accuracy': 92.61988561372635,
 'precision': 0.9263233228916294,
 'recall': 0.9261988561372635,
 'f1': 0.9262340366157426}

In [19]:
y_pred[:100]

array([1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0], dtype=int64)

In [20]:
y_test[:100]

array([1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0], dtype=int64)

In [21]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_true=y_test, 
                 y_pred=y_pred)

array([[7623,  622],
       [ 720, 9219]], dtype=int64)

In [22]:
X_test.head(3)

CustomerType  Age  Class  Flight_Distance  Seat_comfort  Food_drink  \
40827             0   23      2             2215             4           3   
10751             1   51      1             1903             3           3   
88932             1   16      2             3936             3           5   

       Inflight_entertainment  Online_support  Ease_of_Onlinebooking  \
40827                       3               1                      1   
10751                       3               3                      3   
88932                       5               5                      5   

       Onboard_service  Leg_room_service  Online_boarding  
40827                5                 5                1  
10751                3                 4                3  
88932                4                 3                5

In [23]:
a = X_test.iloc[0].to_list()

In [24]:
X_test.shape

(18184, 12)

In [25]:
import numpy as np
a = np.array([1,29,1,250,1,1,1,1,1,1,1,1]).reshape(1, -1)
clf.predict(a)

array([0], dtype=int64)

In [26]:
import pickle
pickle.dump(clf,open('model.pkl','wb'))